# Generated by Django 5.2.7 on 2026-04-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.FloatField(blank=True, null=True)),
                ('mass', models.IntegerField(blank=True, null=True)),
                ('drink_url', models.ImageField(default='', upload_to='drink/')),
            ],
            options={
                'verbose_name': 'Напитки и тд',
                'verbose_name_plural': 'Напитки и тд',
            },
        ),
        migrations.CreateModel(
            name='Kebab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('dop_text', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('mas', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('kebab_url', models.ImageField(upload_to='kebab/')),
            ],
            options={
                'verbose_name': 'Шаурма',
                'verbose_name_plural': 'Шаурма',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shayrma.drink')),
                ('kebab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shayrma.kebab')),
            ],
            options={
                'verbose_name': 'Индивидуальные',
                'verbose_name_plural': 'Индивидуальные',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalPrice', models.FloatField(blank=True, null=True)),
                ('pay', models.CharField(max_length=100)),
                ('Drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shayrma.drink')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shayrma.orders')),
                ('Kebab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shayrma.saved')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='kebab',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shayrma.types'),
        ),
        migrations.AddField(
            model_name='drink',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shayrma.types'),
        ),
    ]
