# Generated by Django 5.2.7 on 2026-04-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kebab',
            name='col_buttons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
