# Generated by Django 5.2.7 on 2026-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0002_kebab_col_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
