# Generated by Django 5.2.7 on 2026-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0003_alter_drink_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='litr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='mass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
