# Generated by Django 5.2.7 on 2026-04-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0004_drink_litr_alter_drink_mass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='litr',
        ),
    ]
