# Generated by Django 5.2.7 on 2026-05-01 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0005_remove_drink_litr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kebab',
            name='dop_text',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='kebab',
        ),
        migrations.AddField(
            model_name='saved',
            name='Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='col',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='col_buttons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='dop_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='kebab_url',
            field=models.ImageField(default=0, upload_to='kebab/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved',
            name='mas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saved',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saved',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shayrma.types'),
            preserve_default=False,
        ),
    ]
