# Generated by Django 5.2.7 on 2026-05-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0006_remove_kebab_dop_text_remove_saved_kebab_saved_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shayrma.types'),
        ),
    ]
