# Generated by Django 5.2.7 on 2026-05-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0007_alter_saved_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='kebab_url',
            field=models.ImageField(blank=True, null=True, upload_to='kebab/'),
        ),
    ]
