# Generated by Django 5.2.7 on 2026-07-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0008_alter_saved_kebab_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Drink',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='drink',
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_url',
            field=models.ImageField(upload_to='kebab/'),
        ),
    ]
