# Generated by Django 5.2.7 on 2026-07-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0009_remove_card_drink_remove_saved_drink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='drink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shayrma.drink'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_url',
            field=models.ImageField(default='', upload_to='drink/'),
        ),
    ]
