# Generated by Django 5.2.7 on 2026-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0010_saved_drink_alter_drink_drink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kebab',
            name='mas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saved',
            name='mas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
