# Generated by Django 5.2.7 on 2026-07-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0011_alter_drink_mass_alter_kebab_mas_alter_saved_mas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='drink',
        ),
        migrations.AlterField(
            model_name='drink',
            name='drink_url',
            field=models.ImageField(default='', upload_to='kebab/'),
        ),
    ]
