# Generated by Django 5.2.7 on 2026-07-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0013_remove_orders_address_card_dop_text_orders_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pay',
        ),
    ]
