# Generated by Django 5.2.7 on 2026-07-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0014_remove_card_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
