# Generated by Django 5.2.7 on 2026-07-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0015_card_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='quantity',
        ),
    ]
