# Generated by Django 5.2.7 on 2026-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0016_remove_card_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='col',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
