# Generated by Django 5.2.7 on 2026-09-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0017_drink_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=200)),
                ('dop_text', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('mas', models.FloatField(blank=True, null=True)),
                ('col_buttons', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
                ('kebab_url', models.ImageField(blank=True, null=True, upload_to='kebab/')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shayrma.types')),
            ],
            options={
                'verbose_name': 'Индивидуальные_(нужны для заказа)',
                'verbose_name_plural': 'Индивидуальные_(нужны для заказа)',
            },
        ),
    ]
