# Generated by Django 5.2.7 on 2026-09-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0018_saved_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Kebab',
        ),
        migrations.RemoveField(
            model_name='saved_invite',
            name='types',
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
        migrations.DeleteModel(
            name='Saved_invite',
        ),
    ]
