# Generated by Django 5.2.7 on 2026-09-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shayrma', '0020_saved_card_kebab_saved_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Kebab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shayrma.saved_invite'),
        ),
    ]
